export const MOVIES: any = [
  {
    Title: 'Prison Break',
    Year: '2005–2017',
    Rated: 'TV-14',
    Released: '29 Aug 2005',
    Runtime: '44 min',
    Genre: 'Action, Crime, Drama, Mystery, Thriller',
    Director: 'N/A',
    Writer: 'Paul Scheuring',
    Actors: 'Dominic Purcell, Wentworth Miller, Robert Knepper, Amaury Nolasco',
    Plot: 'Due to a political conspiracy, an innocent man is sent to death row and his only hope is his brother, who makes it his mission to deliberately get himself sent to the same prison in order to break the both of them out, from the inside.',
    Language: 'English, Arabic, Spanish',
    Country: 'UK, USA',
    Awards: 'Nominated for 2 Golden Globes. Another 4 wins & 26 nominations.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTg3NTkwNzAxOF5BMl5BanBnXkFtZTcwMjM1NjI5MQ@@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '8.3/10'
      }
    ],
    Metascore: 'N/A',
    imdbRating: '8.3',
    imdbVotes: '437,753',
    imdbID: 'tt0455275',
    Type: 'series',
    totalSeasons: '5',
    Response: 'True'
  },
  {
    Title: 'Rambo',
    Year: '2008',
    Rated: 'R',
    Released: '25 Jan 2008',
    Runtime: '92 min',
    Genre: 'Action, Thriller',
    Director: 'Sylvester Stallone',
    Writer: 'Art Monterastelli, Sylvester Stallone, David Morrell (character)',
    Actors: 'Sylvester Stallone, Julie Benz, Matthew Marsden, Graham McTavish',
    Plot: 'In Thailand, John Rambo joins a group of mercenaries to venture into war-torn Burma, and rescue a group of Christian aid workers who were kidnapped by the ruthless local infantry unit.',
    Language: 'English, Burmese, Thai',
    Country: 'Germany, USA',
    Awards: '1 win & 1 nomination.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTI5Mjg1MzM4NF5BMl5BanBnXkFtZTcwNTAyNzUzMw@@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '7.0/10',
      },
      {
        Source: 'Rotten Tomatoes',
        Value: '37%',
      },
      {
        Source: 'Metacritic',
        Value: '46/100',
      },
    ],
    Metascore: '46',
    imdbRating: '7.0',
    imdbVotes: '206,267',
    imdbID: 'tt0462499',
    Type: 'movie',
    DVD: '27 May 2008',
    BoxOffice: '$42,724,402',
    Production: 'Lionsgate',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Terminator 2: Judgment Day',
    Year: '1991',
    Rated: 'R',
    Released: '03 Jul 1991',
    Runtime: '137 min',
    Genre: 'Action, Sci-Fi',
    Director: 'James Cameron',
    Writer: 'James Cameron, William Wisher',
    Actors: 'Arnold Schwarzenegger, Linda Hamilton, Edward Furlong, Robert Patrick',
    Plot: 'A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son, John Connor, from a more advanced and powerful cyborg.',
    Language: 'English, Spanish',
    Country: 'USA',
    Awards: 'Won 4 Oscars. Another 27 wins & 27 nominations.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '8.5/10',
      },
      {
        Source: 'Rotten Tomatoes',
        Value: '93%',
      },
      {
        Source: 'Metacritic',
        Value: '75/100',
      },
    ],
    Metascore: '75',
    imdbRating: '8.5',
    imdbVotes: '926,991',
    imdbID: 'tt0103064',
    Type: 'movie',
    DVD: '31 Mar 1998',
    BoxOffice: '$198,116,802',
    Production: 'TriStar Pictures',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Peppermint',
    Year: '2018',
    Rated: 'R',
    Released: '07 Sep 2018',
    Runtime: '101 min',
    Genre: 'Action, Drama, Thriller',
    Director: 'Pierre Morel',
    Writer: 'Chad St. John',
    Actors: 'Jennifer Garner, John Gallagher Jr., John Ortiz, Juan Pablo Raba',
    Plot: 'Five years after her husband and daughter are killed in a senseless act of violence, a woman comes back from self-imposed exile to seek revenge against those responsible and the system that let them go free.',
    Language: 'English, Spanish',
    Country: 'Hong Kong, USA',
    Awards: 'N/A',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNWVlMjQ3MjItOWE3YS00YTYwLWE0ZDMtZWMyZWY1NzkxNWIwXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '6.5/10',
      },
      {
        Source: 'Rotten Tomatoes',
        Value: '12%',
      },
      {
        Source: 'Metacritic',
        Value: '29/100',
      },
    ],
    Metascore: '29',
    imdbRating: '6.5',
    imdbVotes: '40,781',
    imdbID: 'tt6850820',
    Type: 'movie',
    DVD: '11 Dec 2018',
    BoxOffice: 'N/A',
    Production: 'STXfilms',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Venom',
    Year: '2018',
    Rated: 'PG-13',
    Released: '05 Oct 2018',
    Runtime: '112 min',
    Genre: 'Action, Sci-Fi, Thriller',
    Director: 'Ruben Fleischer',
    Writer: 'Jeff Pinkner (screenplay by), Scott Rosenberg (screenplay by), Kelly Marcel (screenplay by), Jeff Pinkner (screen story by), Scott Rosenberg (screen story by), Todd McFarlane (Marvel\'s Venom Character created by), David Michelinie (Marvel\'s Venom Character created by)',
    Actors: 'Tom Hardy, Michelle Williams, Riz Ahmed, Scott Haze',
    Plot: 'A failed reporter is bonded to an alien entity, one of many symbiotes who have invaded Earth. But the being takes a liking to Earth and decides to protect it.',
    Language: 'English, Mandarin, Malay',
    Country: 'China, USA',
    Awards: 'N/A',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzAwNzUzNjY4MV5BMl5BanBnXkFtZTgwMTQ5MzM0NjM@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '6.7/10',
      },
      {
        Source: 'Metacritic',
        Value: '35/100',
      },
    ],
    Metascore: '35',
    imdbRating: '6.7',
    imdbVotes: '304,804',
    imdbID: 'tt1270797',
    Type: 'movie',
    DVD: '18 Jun 2013',
    BoxOffice: 'N/A',
    Production: 'Vis',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Air Force One',
    Year: '1997',
    Rated: 'R',
    Released: '25 Jul 1997',
    Runtime: '124 min',
    Genre: 'Action, Drama, Thriller',
    Director: 'Wolfgang Petersen',
    Writer: 'Andrew W. Marlowe',
    Actors: 'Harrison Ford, Gary Oldman, Glenn Close, Wendy Crewson',
    Plot: 'Communist Radicals hijack Air Force One with The U.S. President and his family on board. The Vice President negotiates from Washington D.C., while the President, a Veteran, fights to rescue the hostages on board.',
    Language: 'English, Russian',
    Country: 'USA, Germany',
    Awards: 'Nominated for 2 Oscars. Another 7 wins & 10 nominations.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYTk5NWE2ZjAtZmRmOS00ZGYzLWI5ZmUtMDcwODI0YWY0MTRlL2ltYWdlXkEyXkFqcGdeQXVyNjQzNDI3NzY@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '6.5/10',
      },
      {
        Source: 'Rotten Tomatoes',
        Value: '76%',
      },
      {
        Source: 'Metacritic',
        Value: '61/100',
      },
    ],
    Metascore: '61',
    imdbRating: '6.5',
    imdbVotes: '169,688',
    imdbID: 'tt0118571',
    Type: 'movie',
    DVD: '01 Feb 1998',
    BoxOffice: 'N/A',
    Production: 'Columbia Pictures',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Locke',
    Year: '2013',
    Rated: 'R',
    Released: '18 Apr 2014',
    Runtime: '85 min',
    Genre: 'Drama',
    Director: 'Steven Knight',
    Writer: 'Steven Knight',
    Actors: 'Tom Hardy, Olivia Colman, Ruth Wilson, Andrew Scott',
    Plot: 'Ivan Locke, a dedicated family man and successful construction manager, receives a phone call on the eve of the biggest challenge of his career that sets in motion a series of events that threaten his carefully cultivated existence.',
    Language: 'English',
    Country: 'UK, USA',
    Awards: '7 wins & 31 nominations.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTQ1MjE5MzU2M15BMl5BanBnXkFtZTgwNzE4OTMzMTE@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '7.1/10',
      },
      {
        Source: 'Rotten Tomatoes',
        Value: '90%',
      },
      {
        Source: 'Metacritic',
        Value: '81/100',
      },
    ],
    Metascore: '81',
    imdbRating: '7.1',
    imdbVotes: '123,582',
    imdbID: 'tt2692904',
    Type: 'movie',
    DVD: '12 Aug 2014',
    BoxOffice: '$1,326,469',
    Production: 'A24 Films',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Home Alone',
    Year: '1990',
    Rated: 'PG',
    Released: '16 Nov 1990',
    Runtime: '103 min',
    Genre: 'Comedy, Family',
    Director: 'Chris Columbus',
    Writer: 'John Hughes',
    Actors: 'Macaulay Culkin, Joe Pesci, Daniel Stern, John Heard',
    Plot: 'An eight-year-old troublemaker must protect his house from a pair of burglars when he is accidentally left home alone by his family during Christmas vacation.',
    Language: 'English',
    Country: 'USA',
    Awards: 'Nominated for 2 Oscars. Another 10 wins & 4 nominations.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '7.6/10',
      },
      {
        Source: 'Rotten Tomatoes',
        Value: '65%',
      },
      {
        Source: 'Metacritic',
        Value: '63/100',
      },
    ],
    Metascore: '63',
    imdbRating: '7.6',
    imdbVotes: '412,790',
    imdbID: 'tt0099785',
    Type: 'movie',
    DVD: '05 Oct 1999',
    BoxOffice: 'N/A',
    Production: 'Twentieth Century Fox',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Life and the Passion of Christ',
    Year: '2005',
    Rated: 'N/A',
    Released: '01 Mar 2005',
    Runtime: '83 min',
    Genre: 'Documentary, Drama',
    Director: 'Michael Bouson',
    Writer: 'Michael Bouson',
    Actors: 'Jesse Jensen, John Abiskaron, Hal Alpert, Daryl Ball',
    Plot: 'For the first time ever, The Greatest Story Ever Told is proven to be TRUE! This revealing documentary includes interviews with renowned experts who have first-hand knowledge of the ...',
    Language: 'English',
    Country: 'USA',
    Awards: 'N/A',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjEwNjI3NDI0OV5BMl5BanBnXkFtZTcwNjg0MTEzNw@@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '5.4/10',
      },
    ],
    Metascore: 'N/A',
    imdbRating: '5.4',
    imdbVotes: '34',
    imdbID: 'tt0446734',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Matrix',
    Year: '1993–',
    Rated: 'N/A',
    Released: '01 Mar 1993',
    Runtime: '60 min',
    Genre: 'Action, Drama, Fantasy, Thriller',
    Director: 'N/A',
    Writer: 'Grenville Case',
    Actors: 'Nick Mancuso, Phillip Jarrett, Carrie-Anne Moss, John Vernon',
    Plot: 'Steven Matrix is one of the underworld\'s foremost hitmen until his luck runs out, and someone puts a contract out on him. Shot in the forehead by a .22 pistol, Matrix "dies" and finds ...',
    Language: 'English',
    Country: 'Canada',
    Awards: '1 win.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYzUzOTA5ZTMtMTdlZS00MmQ5LWFmNjEtMjE5MTczN2RjNjE3XkEyXkFqcGdeQXVyNTc2ODIyMzY@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '7.8/10',
      },
    ],
    Metascore: 'N/A',
    imdbRating: '7.8',
    imdbVotes: '127',
    imdbID: 'tt0106062',
    Type: 'series',
    totalSeasons: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Return to Eden',
    Year: '1983–',
    Rated: 'N/A',
    Released: '27 Sep 1983',
    Runtime: '267 min',
    Genre: 'Drama, Romance, Thriller',
    Director: 'N/A',
    Writer: 'N/A',
    Actors: 'Rebecca Gilling, James Reyne, Wendy Hughes, James Smillie',
    Plot: 'Wealthy but plain heiress Stephanie Harper marries handsome tennis player Greg Marsden, and thinks she has found true love. That is, until her husband makes a play for her best friend and ...',
    Language: 'English',
    Country: 'Australia, USA',
    Awards: '1 win.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTgzMjU1OTEwNl5BMl5BanBnXkFtZTcwOTMwOTI0MQ@@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '7.4/10',
      },
    ],
    Metascore: 'N/A',
    imdbRating: '7.4',
    imdbVotes: '983',
    imdbID: 'tt0085079',
    Type: 'series',
    totalSeasons: '1',
    Response: 'True',
  },
  {
    Title: 'Guardians of the Galaxy Vol. 2',
    Year: '2017',
    Rated: 'PG-13',
    Released: '05 May 2017',
    Runtime: '136 min',
    Genre: 'Action, Adventure, Comedy, Sci-Fi',
    Director: 'James Gunn',
    Writer: 'James Gunn, Dan Abnett (based on the Marvel comics by), Andy Lanning (based on the Marvel comics by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Jim Starlin (Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Steve Gerber (Howard the Duck created by), Val Mayerik (Howard the Duck created by)',
    Actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    Plot: 'The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord\'s encounter with his father the ambitious celestial being Ego.',
    Language: 'English',
    Country: 'USA',
    Awards: 'Nominated for 1 Oscar. Another 12 wins & 42 nominations.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '7.6/10',
      },
      {
        Source: 'Rotten Tomatoes',
        Value: '84%',
      },
      {
        Source: 'Metacritic',
        Value: '67/100',
      },
    ],
    Metascore: '67',
    imdbRating: '7.6',
    imdbVotes: '507,090',
    imdbID: 'tt3896198',
    Type: 'movie',
    DVD: '22 Aug 2017',
    BoxOffice: '$389,804,217',
    Production: 'Walt Disney Pictures',
    Website: 'N/A',
    Response: 'True',
  }
]
